<?php include('layout/head.php') ?>
    <div class="main-wrapper container mt-4">
        <?php include ('layout/header.phtml') ?>

        <div class="jumbotron">
            <h1 class="display-4">This is the contact page</h1>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </div>


        <!-- Explore Section -->
        <section id="explore" class="my-4">
            <h2>Get in contact with us today!</h2>
        </section>

    </div>
<?php include ('layout/footer.php'); ?>